### ISSUE TITLE
How it's work

### ISSUE THREAD

**Issue by devbysb** [titiseb28/open2300ToJeedom#2]
Hi, 

I have found your script it probably a script to transfert the data of a weather station with open2300 to jeedom.
But what have you configure on jeedom ?

Thank you

**Comment by titiseb28** [comment]
Hello,
it is necessary to create virtual sensors. You must fill in the config.js file as in the example config-sample.js with the apiKey and the id of the virtual sensor

have a good day
Sebastien

**Comment by devbysb** [comment]
I have remove ftp and create virtual sensor and I have created virtual info and map virtual ID.
It works perfectly :) 
thank you

**Comment by titiseb28** [comment]
You're welcome, 
have a good day
